# https://github.com/hmarr/auto-approve-action
name: Auto Approve
on: [push, pull_request_target]

jobs:
  auto-approve:
    if: github.event_name == 'pull_request_target'
    # needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v2
        # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
