# https://commitlint.js.org/
name: commitlint
on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Lint commit message
        run: npx commitlint --from=HEAD~1

      - name: Lint PR title
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.pull_request.title }} | npx commitlint
