# https://commitlint.js.org/
name: commitlint
on: push
jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Lint commit message
        run: npx commitlint --from=HEAD~1
