name: Date
on: push

jobs:
  date:
    runs-on: ubuntu-latest

    steps:
      - run: date +'%Y-%m-%d'
      - run: date +'%Y-%m-%dT%H:%M:%S'

      - run: echo "yyyymmdd=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - run: echo ${{ env.yyyymmdd }}

      - run: echo ${{ github.event.repository.updated_at}}
