# https://docs.github.com/en/actions/learn-github-actions/contexts
name: GitHub Context
on: [push, pull_request]

jobs:
  github-context:
    runs-on: ubuntu-latest

    steps:
      - name: github
        run: echo ${{ github }} | jq

      - name: github.event
        run: echo ${{ github.event }} | jq
