# https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
name: PostgreSQL
on: push

jobs:
  postgres-container:
    runs-on: ubuntu-latest
    container: node
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PGHOST: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres

    steps:
      - name: Install postgresql-client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Connect to PostgreSQL with CLI
        run: psql -c 'SELECT VERSION();'

      - name: Show max connections
        run: psql -c 'SHOW max_connections;'

      - name: Alter max connections
        run: |
          psql -c 'ALTER SYSTEM SET max_connections TO '500';'
          sudo systemctl status postgresql.service
          psql -c 'SHOW max_connections;'

      - name: Install pg
        run: npm install pg

      - name: Connect to PostgreSQL with Node.js
        run: |
          cat > client.js << EOF
          const pg = require('pg');
          const client = new pg.Client();
          client.connect();
          client.query('SELECT VERSION()').then((res) => {
            console.log(res.rows[0]);
            client.end();
          });
          EOF
          node client.js

  postgres-service:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    env:
      PGHOST: localhost
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres

    steps:
      - name: Install postgresql-client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: Connect to PostgreSQL with CLI
        run: psql -c 'SELECT VERSION();'

      - name: Show max connections
        run: psql -c 'SHOW max_connections;'

      - name: Alter max connections
        run: |
          psql -c 'ALTER SYSTEM SET max_connections TO '500';'
          sudo systemctl status postgresql.service
          psql -c 'SHOW max_connections;'

      - name: Install pg
        run: npm install pg

      - name: Connect to PostgreSQL with Node.js
        run: |
          cat > client.js << EOF
          const pg = require('pg');
          const client = new pg.Client();
          client.connect();
          client.query('SELECT VERSION()').then((res) => {
            console.log(res.rows[0]);
            client.end();
          });
          EOF
          node client.js
